chore: don't make bundles for every PR (#1361)
Description
---
Fix broken CI builds. We suffered two different errors (below), for
relatively unknown reasons. To get past the errors I've turned bundles
off in the `tauri-build` workflow. We don't need these bundles made. The
workflow still does a test release compile. it just isn't packaging the
build for any specific platform anymore.

Version was bumped here:
https://github.com/tari-project/universe/pull/1349 to resolve a previous
error.

First error
```
error: failed to compile `tauri-cli v2.2.2`, intermediate artifacts can be found at `/tmp/cargo-install8JNgkx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.80.0 is not supported by the following package:
    home@0.5.11 requires rustc 1.81
```

Second error:
```
     Finished `release` profile [optimized + debuginfo] target(s) in 14m 07s
    Built application at: /home/runner/work/universe/universe/src-tauri/target/release/Tari Universe (Alpha)
    Bundling Tari Universe (Alpha)_0.8.40_amd64.deb (/home/runner/work/universe/universe/src-tauri/target/release/bundle/deb/Tari Universe (Alpha)_0.8.40_amd64.deb)
    Error failed to bundle project:
    - Unable to find a bundled project for the updater
Error: Process completed with exit code 1.
```

Motivation and Context
---
Fix CI

How Has This Been Tested?
---
See if CI is green