fix: telemetry using uninitialized configs (#2746)
Description
---
Telemetry service was accessing configs that aren't initialized
yet(wallet related in this case):
```
thread 'tokio-runtime-worker' panicked at src/internal_wallet.rs:93:24:
InternalWallet is not initialized
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I postponed it until configs are loaded

Additionally:
* Silence manually triggered error. Error is handled in the upper scope,
no need to always log error manually. It's used for displaying on the FE
side. Not important
```
09:12:46 ERROR Error getting node identity: transport error
```