fix: keyring dialog not displayed on deny (#2546)
```rs
.map_err(|e| {
    // Only display once
    block_on(EventsEmitter::emit_show_keyring_dialog());
    anyhow!("Failed to get tari seed from keyring: {e}")
})?
```

```log
thread 'tokio-runtime-worker' panicked at /Users/mpap/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.46.1/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```
<img width="1027" height="645" alt="Screenshot 2025-07-16 at 01 33 42"
src="https://github.com/user-attachments/assets/319b42e4-bddb-48b7-b836-2d2aacee5847"
/>